---
- name: Allow admin group sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin ALL='
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  tags: ["users", "groups", "configuration"]
  when: ansible_os_family == 'Debian'

- name: Allow sudo group sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo   ALL='
    line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  tags: ["users", "groups", "configuration"]
  when: ansible_os_family == 'Debian'

- name: Allow user sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: '{{ item.username }} ALL=NOPASSWD: ALL'
    create: true
    validate: '/usr/sbin/visudo -cf %s'
  with_items: "{{ users }}"
  when: ansible_os_family == 'Debian' and '"sudo" in users.groups'

- name: sudo without password for wheel group
  ansible.builtin.copy:
    content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/wheel_nopasswd
    mode: 0440
  when: ansible_os_family == 'RedHat'
