---
- name: User creation
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: "{{ item.group | default(item.username if users_create_per_user_group else users_group) }}"
    groups: "{{ item.groups | join(',') if 'groups' in item else '' }}"
    append: "{{ item.append | default(omit) }}"
    shell: "{{ item.shell if item.shell is defined else users_default_shell }}"
    password: "{{ item.password | password_hash('sha512') if item.password is defined else '!' }}"
    comment: "{{ item.name if item.name is defined else '' }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default('/home/' + item.username) }}"
    createhome: "{{ 'yes' if users_create_homedirs else 'no' }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
    system: "{{ item.is_system_user | default(omit) | bool or omit }}"
  loop: "{{ users }}"
  tags: ["users", "configuration"]

- name: SSH keys
  ansible.posix.authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    path: "{{ item.0.home | default('/home/' + item.0.username)  }}/.ssh/authorized_keys"
  with_subelements:
    - "{{ users }}"
    - ssh_key
    - skip_missing: true
  tags: ["users", "configuration"]

- name: Setup user profiles
  ansible.builtin.blockinfile:
    block: "{{ item.profile }}"
    dest: "{{ item.home | default('/home/' + item.username) }}/{{ profile_name  }}"
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username if users_create_per_user_group else users_group) }}"
    mode: 0644
    create: true
    marker_begin: "<!-- BEGIN USERS SETUP -->"
    marker_end: "<!-- BEGIN USERS SETUP -->"
  when: users_create_homedirs and item.profile is defined
  with_items: "{{ users }}"

- name: Enable SSH TCP Forwarding
  ansible.builtin.lineinfile:
    path: "{{ item.home | default('/home/' + item.username) }}/.ssh/config"
    line: "AllowTcpForwarding yes"
    regexp: '^#AllowTcpForwarding yes$'
    create: true
    mode: 0600
  when: item.enable_ssh_tcp_forwarding is defined and item.enable_ssh_tcp_forwarding
  with_items: "{{ users }}"
