---
- name: Create group(s)
  ansible.builtin.include_tasks: create-groups.yaml

- name: Create admin group(s)
  ansible.builtin.include_tasks: create-admin-group.yaml

- name: Create user(s)
  ansible.builtin.include_tasks: create-users.yaml
